---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes
    
- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes 

- name: "Install python packages"
  become: yes
  apt:
    name: ["python3-pip","build-essential","libssl-dev","libffi-dev","python3-dev"]
    
- name: "Remove non-required deps"
  become: yes
  apt:
    autoremove: yes    

- name: "installing npm & nodejs"
  become: yes
  apt:
    name: ["nodejs","npm"]
    update_cache: yes
    state: latest

- name: Install n
  become: yes
  npm:
    name: n
    global: yes
    production: yes

- name: install nodejs v13.8.0
  become: yes
  shell: n 13.8.0

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present      